<?php
/**
 * Language labels for tooltips of RTE HtmalArea (extension: rte_pb_htmlarea)
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'bold' => 'Bold',
		'italic' => 'Italic',
		'underline' => 'Underline',
		'strikethrough' => 'Strikethrough',
		'subscript' => 'Subscript',
		'superscript' => 'Superscript',
		'justifyleft' => 'Justify Left',
		'justifycenter' => 'Justify Center',
		'justifyright' => 'Justify Right',
		'justifyfull' => 'Justify Full',
		'insertorderedlist' => 'Ordered List',
		'insertunorderedlist' => 'Bulleted List',
		'outdent' => 'Decrease Indent',
		'indent' => 'Increase Indent',
		'forecolor' => 'Font Color',
		'hilitecolor' => 'Background Color',
		'inserthorizontalrule' => 'Horizontal Rule',
		'createlink' => 'Insert Web Link',
		'insertimage' => 'Insert/Modify Image',
		'inserttable' => 'Insert Table',
		'htmlmode' => 'Toggle HTML Source',
		'popupeditor' => 'Enlarge Editor',
		'about' => 'About this editor',
		'showhelp' => 'Help using editor',
		'textindicator' => 'Current style',
		'undo' => 'Undoes your last action',
		'redo' => 'Redoes your last action',
		'cut' => 'Cut selection',
		'copy' => 'Copy selection',
		'paste' => 'Paste from clipboard',
		'lefttoright' => 'Direction left to right',
		'righttoleft' => 'Direction right to left',
		'removeformat' => 'Remove formatting',
		'print' => 'Print document',
		'killword' => 'Clear MSOffice tags',
		'fontname' => 'Font',
		'fontsize' => 'Font size',
		'formatblock' => 'Type of paragragh',
	),
	'dk' => Array (
	),
	'de' => Array (
		'bold' => 'Fett',
		'italic' => 'Kursiv',
		'underline' => 'Unterstrichen',
		'strikethrough' => 'Durchgestrichen',
		'subscript' => 'Tiefgestellt',
		'superscript' => 'Hochgestellt',
		'justifyleft' => 'Links',
		'justifycenter' => 'Zentrieren',
		'justifyright' => 'Rechts',
		'justifyfull' => 'Blocksatz',
		'insertorderedlist' => 'Nummerierung',
		'insertunorderedlist' => 'Punktliste',
		'outdent' => 'Einzug verkleinern',
		'indent' => 'Einzug vergrößern',
		'forecolor' => 'Zeichenfarbe',
		'hilitecolor' => 'Hintergrundfarbe',
		'inserthorizontalrule' => 'Horizontale Linie',
		'createlink' => 'Link einfügen',
		'insertimage' => 'Bild einfügen / verändern',
		'inserttable' => 'Tabelle einfügen',
		'htmlmode' => 'Zur HTML-Ansicht wechseln',
		'popupeditor' => 'Editor-Fenster vergrößern',
		'about' => 'Über diesen Editor',
		'showhelp' => 'Hilfe',
		'textindicator' => 'Momentaner Style',
		'undo' => 'Macht die letzte Aktion rückgängig',
		'redo' => 'Wiederholt die letzte Aktion',
		'cut' => 'Auswahl ausschneiden',
		'copy' => 'Auswahl kopieren',
		'paste' => 'Aus der Zwischenablage einfügen',
		'lefttoright' => 'Schreibrichtung von links nach rechts',
		'righttoleft' => 'Schreibrichtung von rechts nach links',
		'removeformat' => 'Formatierung entfernen',
		'print' => 'Das Dokument drucken',
		'killword' => 'MSOffice <o:> entfernen',
		'fontname' => 'Zeichensatz',
		'fontsize' => 'Zeichengröße',
		'formatblock' => 'Absatzart',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
		'bold' => 'Gras',
		'italic' => 'Italique',
		'underline' => 'Souligné',
		'strikethrough' => 'Barré',
		'subscript' => 'Indice inférieur',
		'superscript' => 'Indice supérieur',
		'justifyleft' => 'Justifié à  gauche',
		'justifycenter' => 'Centré',
		'justifyright' => 'Justifié à  droite',
		'justifyfull' => 'Justifié à  gauche et à  droite',
		'insertorderedlist' => 'Liste numérotée',
		'insertunorderedlist' => 'Liste à  puces',
		'outdent' => 'Diminuer le retrait',
		'indent' => 'Augmenter le retrait',
		'forecolor' => 'Couleur du texte',
		'hilitecolor' => 'Couleur du fond',
		'inserthorizontalrule' => 'Ligne horizontale',
		'createlink' => 'Insérer un lien',
		'insertimage' => 'Insérer une image',
		'inserttable' => 'Insérer une table',
		'htmlmode' => 'Mode source HTML',
		'popupeditor' => 'Agrandir l\'éditeur',
		'about' => 'A propos de cet éditeur',
		'showhelp' => 'Aide sur l\'éditeur',
		'textindicator' => 'Style courant',
		'undo' => 'Annuler la dernière action',
		'redo' => 'Refaire la dernière action',
		'cut' => 'Couper la sélection',
		'copy' => 'Copier la sélection',
		'paste' => 'Coller depuis le presse-papiers',
		'lefttoright' => 'Texte de gauche à droite',
		'righttoleft' => 'Texte de droite à gauche',
		'removeformat' => 'Enlever le formatage',
		'print' => 'Imprimer le document',
		'killword' => 'Enlever les balises MSOffice',
		'fontname' => 'Police',
		'fontsize' => 'Taille de la police',
		'formatblock' => 'Type de paragraghe',
	),
	'es' => Array (
		'bold' => 'Negrita',
		'italic' => 'Cursiva',
		'underline' => 'Subrayado',
		'strikethrough' => 'Tachado',
		'subscript' => 'Subíndice',
		'superscript' => 'Superíndice',
		'justifyleft' => 'Alinear a la izquierda',
		'justifycenter' => 'Alinear al centro',
		'justifyright' => 'Alinear a la derecha',
		'justifyfull' => 'Justificar',
		'insertorderedlist' => 'Lista ordenada',
		'insertunorderedlist' => 'Lista no ordenada',
		'outdent' => 'Reducir sangría',
		'indent' => 'Aumentar sangría',
		'forecolor' => 'Color del texto',
		'hilitecolor' => 'Color del fondo',
		'inserthorizontalrule' => 'Línea horizontal',
		'createlink' => 'Insertar enlace',
		'insertimage' => 'Insertar imagen',
		'inserttable' => 'Insertar tabla',
		'htmlmode' => 'Ver código HTML',
		'popupeditor' => 'Ampliar editor',
		'about' => 'Acerca de este editor',
		'showhelp' => 'Ayuda',
		'textindicator' => 'Estilo actual',
		'undo' => 'Deshacer la última acción',
		'redo' => 'Volver a efectuar la última acción',
		'cut' => 'Cortar la selección',
		'copy' => 'Copiar la selección',
		'paste' => 'Pegar el contenido del portapapeles',
		'lefttoright' => 'De la izquierda a la derecha',
		'righttoleft' => 'De la derecha a la izquierda',
		'removeformat' => 'Borrar formato',
		'print' => 'Imprimir el documento',
	),
	'nl' => Array (
		'bold' => 'Vet',
		'italic' => 'Schuinschrift',
		'underline' => 'Onderstrepen',
		'strikethrough' => 'Doorhalen',
		'subscript' => 'Subscript',
		'superscript' => 'Superscript',
		'justifyleft' => 'Links uitlijnen',
		'justifycenter' => 'Gecentreerd uitlijnen',
		'justifyright' => 'Rechts uitlijnen',
		'justifyfull' => 'Uitvullen',
		'insertorderedlist' => 'Nummering',
		'insertunorderedlist' => 'Opsommingstekens',
		'outdent' => 'Inspringen verkleinen',
		'indent' => 'Inspringen vergroten',
		'forecolor' => 'Tekstkleur',
		'hilitecolor' => 'Achtergrond kleur',
		'inserthorizontalrule' => 'Horizontale streep',
		'createlink' => 'Hyperlink invoegen',
		'insertimage' => 'Invoegen/aanpassen afbeelding',
		'inserttable' => 'Invoegen tabel',
		'htmlmode' => 'Wissel HTML broncode',
		'popupeditor' => 'Vergroot editor',
		'about' => 'Over deze editor',
		'showhelp' => 'Hulp over het gebruik van deze editor',
		'textindicator' => 'Huidige stijl',
		'undo' => 'Ongedaan maken laatste actie',
		'redo' => 'Opnieuw laatste actie',
		'cut' => 'Knip selectie',
		'copy' => 'Kopieer selectie',
		'paste' => 'Plak van het klipbord',
		'lefttoright' => 'Rechts naar links',
		'righttoleft' => 'Links naar rechts',
		'removeformat' => 'Verwijderen opmaak',
		'print' => 'Print document',
		'killword' => 'Verwijderen MSOffice tags',
		'fontname' => 'Lettertype',
		'fontsize' => 'Lettergrootte',
		'formatblock' => 'Soort paragraaf',
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'bold' => 'Vahvennettu',
		'italic' => 'Kursiivi',
		'underline' => 'Alleviivaus',
		'strikethrough' => 'Läpi merkin',
		'subscript' => 'Alamerkki',
		'superscript' => 'Ylämerkki',
		'justifyleft' => 'Tasaa vasemmalle',
		'justifycenter' => 'Tasaa keskelle',
		'justifyright' => 'Tasaa oikealle',
		'justifyfull' => 'Tasaa koko alueelle',
		'insertorderedlist' => 'Järjestetty lista',
		'insertunorderedlist' => 'Etumerkillinen lista',
		'outdent' => 'Vähennä sisennystä',
		'indent' => 'Lisää sisennystä',
		'forecolor' => 'Merkin väri',
		'hilitecolor' => 'Taustan väri',
		'inserthorizontalrule' => 'Vaakaerotin',
		'createlink' => 'Lisää weblinkki',
		'insertimage' => 'Lisää/muokkaa kuvaa',
		'inserttable' => 'Lisää taulukko',
		'htmlmode' => 'Vaihda HTMLlähdekoodin näyttöä',
		'popupeditor' => 'Suurenna muokkaajaa',
		'about' => 'Yleistä muokkaajasta',
		'showhelp' => 'Muokkaajan avut',
		'textindicator' => 'Nykyinen tyyli',
		'undo' => 'Palauta',
		'redo' => 'Tee uudestaan',
		'cut' => 'Leikkauksen valinta',
		'copy' => 'Kopioinnin valinta',
		'paste' => 'Liitä leikepöydältä',
		'lefttoright' => 'Suunta vasemmalta oikealle',
		'righttoleft' => 'Suunta oikealta vasemmalle',
		'removeformat' => 'Poista muotoilu',
		'print' => 'Tulosta asiakirja',
		'killword' => 'Poista MSOffice tagit',
		'fontname' => 'Merkki',
		'fontsize' => 'Merkin koko',
		'formatblock' => 'Kappaleen tyyppi',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
		'bold' => 'Æèðíûé',
		'italic' => 'Íàêëîííûé',
		'underline' => 'Ïîä÷¸ðêíóòûé',
		'strikethrough' => 'Çà÷¸ðêíóòûé',
		'subscript' => 'Ñíèçó',
		'superscript' => 'Ñâåðõó',
		'justifyleft' => 'Âûðàâíèå ïî ëåâîìó êðàþ',
		'justifycenter' => 'Âûðàâíèå ïî öåíòðó',
		'justifyright' => 'Âûðàâíèå ïî ïðàâîìó êðàþ',
		'justifyfull' => 'Âûðàâíèå ïî îáîèì êðàÿì',
		'insertorderedlist' => 'Íóìåðîâàíûé ñïèñîê',
		'insertunorderedlist' => 'Íåíóìåðîâàíûé ñïèñîê',
		'outdent' => 'Óìåíüøèòü îòñòóï',
		'indent' => 'Óâåëè÷èòü îòñòóï',
		'forecolor' => 'Öâåò øðèôòà',
		'hilitecolor' => 'Öâåò ôîíà',
		'inserthorizontalrule' => 'Ãîðèçîíòàëüíûé ðàçäåëèòåëü',
		'createlink' => 'Âñòàâèòü ññûëêó',
		'insertimage' => 'Âñòàâèòü êàðòèíêó',
		'inserttable' => 'Âñòàâèòü òàáëèöó',
		'htmlmode' => 'Ïåðåêëþ÷èòüñÿ íà ðåäàêòèðîâàíèå HTML',
		'popupeditor' => 'Óâåëè÷èòü ðåäàêòîð',
		'about' => 'Îá ýòîì ðåäàêòîðå',
		'showhelp' => 'Ïîäñêàçêà',
		'textindicator' => 'Òåêóùèé ñòèëü',
		'undo' => 'Îòìåíÿåò ïîñëåäíåå äåéñòâèå',
		'redo' => 'Âûïîëíÿåò ïîñëåäíåå äåéñòâèå ñíîâà',
		'cut' => 'Âûðåçàòü âûáðàíîå',
		'copy' => 'Ñêîïèðîâàòü âûáðàíîå',
		'paste' => 'Âñòàâèòü èç áóôåðà îáìåíà',
		'lefttoright' => 'Íàïðàâëåíèå ñëåâà íàïðàâî',
		'righttoleft' => 'Íàïðàâëåíèå ñïðàâà íàëåâî',
		'removeformat' => 'Óäàëèòü ôîðìàòèðîâàíèå',
		'print' => 'Ïå÷àòàòü äîêóìåíò',
		'killword' => 'Óáðàòü âñå òàãè MSOffice',
		'fontname' => 'Øðèôò',
		'fontsize' => 'Ðàçìåð øðèôòà',
		'formatblock' => 'Òèï àáçàöà',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>