<?php
/**
 * Language labels for dialogs of RTE HtmalArea (extension: rte_pb_htmlarea)
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'OK' => 'OK',
		'Cancel' => 'Cancel',
		'Alignment:' => 'Alignment:',
		'Alignment not set' => 'Not set',
		'Left' => 'Left',
		'Center' => 'Center',
		'Right' => 'Right',
		'Texttop' => 'Texttop',
		'Absmiddle' => 'Absmiddle',
		'Baseline' => 'Baseline',
		'Absbottom' => 'Absbottom',
		'Bottom' => 'Bottom',
		'Middle' => 'Middle',
		'Top' => 'Top',
		'Layout' => 'Layout',
		'Spacing' => 'Spacing',
		'Horizontal:' => 'Horizontal:',
		'Horizontal padding' => 'Horizontal padding',
		'Vertical:' => 'Vertical:',
		'Vertical padding' => 'Vertical padding',
		'Border thickness:' => 'Border thickness:',
		'Leave empty for no border' => 'Leave empty for no border',
		'Insert/Modify Link' => 'Insert/Modify Link',
		'Title (tooltip):' => 'Title (tooltip):',
		'URL:' => 'URL:',
		'Insert Table' => 'Insert Table',
		'Rows:' => 'Rows:',
		'Number of rows' => 'Number of rows',
		'You must enter a number of rows' => 'You must enter a number of rows',
		'Cols:' => 'Cols:',
		'Number of columns' => 'Number of columns',
		'You must enter a number of colums' => 'You must enter a number of columns',
		'Width:' => 'Width:',
		'Width of the table' => 'Width of the table',
		'Percent' => 'Percent',
		'Pixels' => 'Pixels',
		'Em' => 'Em',
		'Width unit' => 'Width unit',
		'Positioning of this table' => 'Positioning of this table',
		'Cell spacing:' => 'Cell spacing:',
		'Space between adjacent cells' => 'Space between adjacent cells',
		'Cell padding:' => 'Cell padding:',
		'Space between content and border in cell' => 'Space between content and border in cell',
		'Insert Image' => 'Insert Image',
		'Image URL:' => 'Image URL:',
		'Enter the image URL here' => 'Enter the image URL here',
		'Preview' => 'Preview',
		'Preview the image in a new window' => 'Preview the image in a new window',
		'Alternate text:' => 'Alternate text:',
		'Positioning of this image' => 'Positioning of this image',
		'Image Preview:' => 'Image Preview:',
		'Select Color' => 'Select Color',
		'About HTMLArea' => 'About HTMLArea',
		'About' => 'About',
		'Compiled on March 1, 2004 19:37 GMT' => 'Compiled on March 1, 2004 19:37 GMT',
		'Go to' => 'Go to',
		'latest_release' => '[latest milestone release]',
		'free_editor' => 'A free WYSIWYG editor replacement for <textarea> fields.',
		'Mozilla_or_IE' => 'For Mozilla 1.3+ (any platform) or Internet Explorer 5.5+ (Windows).',
		'All rights reserved.' => 'All Rights Reserved.',
		'Project resources' => 'Project resources',
		'Project page' => 'Project page',
		'Anonymous CVS access' => 'Anonymous CVS access',
		'Bug system' => 'Bug system',
		'Forum' => 'Forum',
		'Last public release' => 'Last public release',
		'For download section please see the' => 'For download section please see the',
		'Version' => 'Version',
		'developed and maintained by' => 'developed and maintained by',
		'Thanks' => 'Thanks',
		'Thank you' => 'Thank you',
		'would_like_to_thank' => 'would like to thank the following companies/persons for their donations to support development of HTMLArea (listed alphabetically):',
		'Also many thanks to all people at' => 'Also many thanks to all people at',
		'for contributing translations, feedback, bug reports and fixes.' => 'for contributing translations, feedback, bug reports and fixes.',
		'project_would_not_exist' => 'Last but not least, this project wouldn\'t have existed without',
		'Licence' => 'Licence',
		'htmlArea License (based on BSD license)' => 'htmlArea License (based on BSD license)',
		'Plugins' => 'Plugins',
		'Name' => 'Name',
		'Developer' => 'Developer',
		'Sponsored by' => 'Sponsored by',
		'plugin_terms' => 'means that the plugin is distributed under the same terms as HTMLArea itself.',
		'likely_included' => 'Such plugins are likely to be those included in the official HTMLArea distribution.',
		'The following plugins have been loaded.' => 'The following plugins have been loaded.',
		'No plugins have been loaded.' => 'No plugins have been loaded.',
		'User agent reports:' => 'User agent reports:',
		'I agree' => 'I agree',
	),
	'dk' => Array (
	),
	'de' => Array (
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
		'OK' => 'OK',
		'Cancel' => 'Annuler',
		'Alignment:' => 'Alignement:',
		'Alignment not set' => 'Non spécifié',
		'Left' => 'À gauche',
		'Center' => 'Au centre',
		'Right' => 'À droite',
		'Texttop' => 'Texttop',
		'Absmiddle' => 'Absmiddle',
		'Baseline' => 'Ligne de base',
		'Absbottom' => 'Absbottom',
		'Bottom' => 'En bas',
		'Middle' => 'Au milieu',
		'Top' => 'En haut',
		'Layout' => 'Disposition',
		'Spacing' => 'Espacement',
		'Horizontal:' => 'Alignement horizontal:',
		'Horizontal padding' => 'Horizontal padding',
		'Vertical:' => 'Alignement vertical:',
		'Vertical padding' => 'Position de la table',
		'Border thickness:' => 'Épaisseur des bordures:',
		'Leave empty for no border' => 'Laisser libre si sans bordure',
		'Insert/Modify Link' => 'Insérer/Modifier un lien',
		'Title (tooltip):' => 'Title (tooltip):',
		'URL:' => 'URL:',
		'Insert Table' => 'Insérer une table',
		'Rows:' => 'Rangées:',
		'Number of rows' => 'Nombre de rangées',
		'You must enter a number of rows' => 'Veuillez spécifier le nombre de rangées.',
		'Cols:' => 'Colonnes:',
		'Number of columns' => 'Nombre de colonnes',
		'You must enter a number of colums' => 'Veuillez spécifier le nombre de colonnes.',
		'Width:' => 'Largeur de la table:',
		'Width of the table' => 'Largeur de la table',
		'Percent' => '%',
		'Pixels' => 'px',
		'Em' => 'em',
		'Width unit' => 'Unité de largeur',
		'Positioning of this table' => 'Position de la table',
		'Cell spacing:' => 'Entre les cellules:',
		'Space between adjacent cells' => 'Espace entre cellules adjacentes',
		'Cell padding:' => 'Dans les cellules:',
		'Space between content and border in cell' => 'Espace entre le contenu et le bord de la cellule',
		'Insert Image' => 'Insérer une image',
		'Image URL:' => 'Image URL:',
		'Enter the image URL here' => 'Enter the image URL here',
		'Preview' => 'Preview',
		'Preview the image in a new window' => 'Preview the image in a new window',
		'Alternate text:' => 'Alternate text:',
		'Positioning of this image' => 'Positioning of this image',
		'Image Preview:' => 'Image Preview:',
		'Select Color' => 'Choix de couleur',
		'About HTMLArea' => 'À propos de HTMLArea',
		'About' => 'À propos de...',
		'Compiled on March 1, 2004 19:37 GMT' => 'Compilé le 1er mars 2004 à 19:37 GMT',
		'Go to' => 'Aller à ',
		'latest_release' => '[dernière édition]',
		'free_editor' => 'Un éditeur WYSIWYG libre pour les champs <textarea>.',
		'Mozilla_or_IE' => 'Pour Mozilla 1.3+ (toutes plate-formes) ou Internet Explorer 5.5+ (Windows).',
		'All rights reserved.' => 'Tous droits réservés.',
		'Project resources' => 'Ressources du projet',
		'Project page' => 'Page du projet',
		'Anonymous CVS access' => 'Accès CVS anonyme',
		'Bug system' => 'Système de suivi des problèmes',
		'Forum' => 'Forum',
		'Last public release' => 'Dernière édition publique',
		'For download section please see the' => 'Pour la section de téléchargement voir la',
		'Version' => 'Version',
		'developed and maintained by' => 'développée et maintenue par',
		'Thanks' => 'Remerciements',
		'Thank you' => 'Merci',
		'would_like_to_thank' => 'désire remercier les sociétés et personnes suivantes pour leurs dons en appui au développement de HTMLArea (en ordre alphabétique):',
		'Also many thanks to all people at' => 'Grand merci aussi à tous les participants de',
		'for contributing translations, feedback, bug reports and fixes.' => 'pour leurs contributions: traductions, feedback, rapports de problèmes et correctifs.',
		'project_would_not_exist' => 'Finalement, ce projet n\'aurait pas existé sans l\'appui',
		'Licence' => 'Licence',
		'htmlArea License (based on BSD license)' => 'Licence htmlArea (basée sur la licence BSD)',
		'Plugins' => 'Modules',
		'Name' => 'Nom',
		'Developer' => 'Développé par',
		'Sponsored by' => 'Commandité par',
		'plugin_terms' => 'siginifie que le module est distribué selon les mêmes termes que HTMLArea lui-même.',
		'likely_included' => 'De tels modules sont susceptibles d\'être inclus dans la distribution officielle de HTMLArea.',
		'The following plugins have been loaded.' => 'Les modules suivants sont installés.',
		'No plugins have been loaded.' => 'Aucun module n\'est installé.',
		'User agent reports:' => 'Votre fureteur actuel:',
		'I agree' => 'J\'accepte',
	),
	'es' => Array (
		'OK' => 'Aceptar',
		'Cancel' => 'Cancelar',
		'Alignment:' => 'Alienación:',
		'Alignment not set' => 'Sín specificar',
		'Left' => 'A la izquierda',
		'Center' => 'Al centro',
		'Right' => 'A la derecha',
		'Texttop' => 'Texttop',
		'Absmiddle' => 'Absmiddle',
		'Baseline' => 'Línea base',
		'Absbottom' => 'Absbottom',
		'Bottom' => 'Abajo',
		'Middle' => 'Al medio',
		'Top' => 'Arriba',
		'Layout' => 'Disposición',
		'Spacing' => 'Márgenes de las celdas',
		'Horizontal:' => 'Alienación horizontal:',
		'Horizontal padding' => 'Horizontal padding',
		'Vertical:' => 'Alienación vertical:',
		'Vertical padding' => 'Posición de la tabla',
		'Border thickness:' => 'Anchura del marco:',
		'Leave empty for no border' => 'Dejar vacío cuando no hay marco',
		'Insert/Modify Link' => 'Insertar/Cambiar enlace',
		'Title (tooltip):' => 'Title (tooltip):',
		'URL:' => 'URL:',
		'Insert Table' => 'Insertar tabla',
		'Rows:' => 'Filas:',
		'Number of rows' => 'Número de filas',
		'You must enter a number of rows' => 'Se requiere el número de filas.',
		'Cols:' => 'Columnas:',
		'Number of columns' => 'Número de columnas',
		'You must enter a number of colums' => 'Se requiere el número de columnas.',
		'Width:' => 'Anchura de la tabla:',
		'Width of the table' => 'Anchura de la tabla',
		'Percent' => '%',
		'Pixels' => 'px',
		'Em' => 'em',
		'Width unit' => 'Tipo de valor',
		'Positioning of this table' => 'Posición de la tabla',
		'Cell spacing:' => 'Entre celdas:',
		'Space between adjacent cells' => 'Espacio entre celdas',
		'Cell padding:' => 'Dentro de las celdas:',
		'Space between content and border in cell' => 'Espacio entre el borde de la celda y sus contenidos',
		'Insert Image' => 'Insertar imagen',
		'Image URL:' => 'Image URL:',
		'Enter the image URL here' => 'Enter the image URL here',
		'Preview' => 'Preview',
		'Preview the image in a new window' => 'Preview the image in a new window',
		'Alternate text:' => 'Alternate text:',
		'Positioning of this image' => 'Positioning of this image',
		'Image Preview:' => 'Image Preview:',
		'Select Color' => 'Selección de color',
		'About HTMLArea' => 'Acerca de HTMLArea',
		'About' => 'Acerca de...',
		'Compiled on March 1, 2004 19:37 GMT' => 'Publicado el 1º de marzo de 2004 a las 19:37 GMT',
		'Go to' => 'Ir a',
		'latest_release' => '[última edición]',
		'free_editor' => 'Un editor WYSIWYG libre para editar campos <textarea>.',
		'Mozilla_or_IE' => 'Para Mozilla 1.3+ (cualquier sistema) o Internet Explorer 5.5+ (Windows).',
		'All rights reserved.' => 'Reservados todos los derechos.',
		'Project resources' => 'Recursos del proyecto',
		'Project page' => 'Página del proyecto',
		'Anonymous CVS access' => 'Acceso CVS anónimo',
		'Bug system' => 'Sistema de problemas',
		'Forum' => 'Forum',
		'Last public release' => 'Última edición',
		'For download section please see the' => 'Para acceder a la sección de descarga, visite la',
		'Version' => 'Versión',
		'developed and maintained by' => 'desarollada y mantenida por',
		'Thanks' => 'Agradecimientos',
		'Thank you' => 'Gracias',
		'would_like_to_thank' => 'desea agradecer las siguientes empresas y personas por sus donaciones de apoyo al desarollo de HTMLArea (lista alfabética):',
		'Also many thanks to all people at' => 'También muchas gracias a toda la gente de',
		'for contributing translations, feedback, bug reports and fixes.' => 'por sus contribuciones: traducciones, feedback, informes de problemas y correcciones.',
		'project_would_not_exist' => 'Por fin y sobra todo, este proyecto no existaría sín el apoyo de',
		'Licence' => 'Licencia',
		'htmlArea License (based on BSD license)' => 'Licencia htmlArea (basada en la licencia BSD)',
		'Plugins' => 'Módulos',
		'Name' => 'Nombre',
		'Developer' => 'Desarollado por',
		'Sponsored by' => 'Patrocinado por',
		'plugin_terms' => 'significa que el modulo se distribuye bajo los mismos términos que HTMLArea proprio.',
		'likely_included' => 'Estos módulos se incluyen generalmente en la distribución oficial de HTMLArea.',
		'The following plugins have been loaded.' => 'Los siguientes módulos han sido cargados.',
		'No plugins have been loaded.' => 'Ningún módulo cargado.',
		'User agent reports:' => 'Su navegador:',
		'I agree' => 'Acepto',
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'OK' => 'OK',
		'Cancel' => 'Peruuta',
		'Alignment:' => 'Keskitys',
		'Alignment not set' => 'Ei asetettu',
		'Left' => 'Vasen',
		'Center' => 'Keskelle',
		'Right' => 'Oikea',
		'Texttop' => 'Tekstissä ylös',
		'Absmiddle' => 'Abs. keskelle',
		'Baseline' => 'Peruslinja',
		'Absbottom' => 'Abs.alas',
		'Bottom' => 'Alas',
		'Middle' => 'Keskelle',
		'Top' => 'Ylös',
		'Layout' => 'Muoto',
		'Spacing' => 'Välistys',
		'Horizontal:' => 'Vaakataso:',
		'Horizontal padding' => 'Vaakatason välistys',
		'Vertical:' => 'Pysty:',
		'Vertical padding' => 'Pystyvälistys',
		'Border thickness:' => 'Rajan paksuus',
		'Leave empty for no border' => 'Jätä tyhjäksi jos ei rajaa',
		'Insert/Modify Link' => 'Lisää/Muotoile linkkiä',
		'Title (tooltip):' => 'Otsikko (tooltip):',
		'URL:' => 'URL:',
		'Insert Table' => 'Lisää taulukko',
		'Rows:' => 'Rivit:',
		'Number of rows' => 'Rivien lukumäärä',
		'You must enter a number of rows' => 'Sinun tulee antaa rivien lukumäärä',
		'Cols:' => 'Sarakkeet:',
		'Number of columns' => 'Sarakkeiden lukumäärä',
		'You must enter a number of colums' => 'Sinun tulee antaa sarakkeiden lukumäärä',
		'Width:' => 'Leveys:',
		'Width of the table' => 'Taulukon leveys',
		'Percent' => 'Prosenteissa',
		'Pixels' => 'Pixeleissä',
		'Em' => 'Em',
		'Width unit' => 'Leveyden yksikkö',
		'Positioning of this table' => 'Tämän taulukon sijoitus',
		'Cell spacing:' => 'Solun välistys:',
		'Space between adjacent cells' => 'Tila kahden solun välillä',
		'Cell padding:' => 'Solun täyttö:',
		'Space between content and border in cell' => 'Tila sisällön ja rajan välillä solussa',
		'Insert Image' => 'Lisää kuva',
		'Image URL:' => 'Kuvan URL:',
		'Enter the image URL here' => 'Anna kuvan URL tähän',
		'Preview' => 'Esikatsele',
		'Preview the image in a new window' => 'Esikatsele kuvaa uudessa ikkunassa',
		'Alternate text:' => 'Vaihtoehtoinen teksti',
		'Positioning of this image' => 'Tämän kuvan sijoitus',
		'Image Preview:' => 'Kuvan esikatselu:',
		'Select Color' => 'Valitse väri',
		'About HTMLArea' => 'Yleistä HTMLAreasta',
		'About' => 'Yleistä',
		'Compiled on March 1, 2004 19:37 GMT' => 'Käännetty maaliskuun1, 2004 19:37 GMT',
		'Go to' => 'Mene',
		'latest_release' => '[viimeinen virstanpyölväs julkistus]',
		'free_editor' => 'Vapaa WYSIWYG muokkain <textarea> tiedoille.',
		'Mozilla_or_IE' => 'Tarkoitettu Mozilla 1.3+ ja Internet Explorer 5.5+ (Windows) selaimille.',
		'All rights reserved.' => 'Kaikki oikeudet varattu.',
		'Project resources' => 'Projektin resurssit',
		'Project page' => 'Projektisivu',
		'Anonymous CVS access' => 'Anonyymi CVS palvelu',
		'Bug system' => 'Virhe järjestelmä',
		'Forum' => 'Foorumi',
		'Last public release' => 'Viimeinen julkinen julkistus',
		'For download section please see the' => 'Latausta (downloadia) varten katso kappaletta',
		'Version' => 'Versio',
		'developed and maintained by' => 'kehittänyt ja ylläpitää',
		'Thanks' => 'Kiitos',
		'Thank you' => 'Kiitos Sinulle',
		'would_like_to_thank' => 'haluamme kiittää seuraavia yrityksiä/henkilöitä lahjoituksistaan tukea HTMLArean kehitystä (aakkosellinen luettelo):',
		'Also many thanks to all people at' => 'Parhaimmat kiitokset myös kaikille henkilöille',
		'for contributing translations, feedback, bug reports and fixes.' => 'tukevista käännöksistä, palautteesta, virheraporteista sekä korjauksista.',
		'project_would_not_exist' => 'Ja viimeiseksi, projektia ei olisi ellei',
		'Licence' => 'Lisenssi',
		'htmlArea License (based on BSD license)' => 'htmlArea lisenssi (perustuu BSD lisenssiin)',
		'Plugins' => 'Pluginit',
		'Name' => 'Nimi',
		'Developer' => 'Kehittäjä',
		'Sponsored by' => 'Sponsoroinut',
		'plugin_terms' => 'tarkoittaa että plugin on jakelussa samoin ehdoin kuin HTMLArea itse.',
		'likely_included' => 'Kuten sellaiset pluginit jotka on lisätty viralliseen HTMLArea jakeluun.',
		'The following plugins have been loaded.' => 'Seuraavat pluginit on ladattu.',
		'No plugins have been loaded.' => 'Plugineja ei ole ladattu.',
		'User agent reports:' => 'Käyttäjäagentti raportoi:',
		'I agree' => 'Hyväksyn',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>