<?php
/**
 * Language labels for plugin ContextMenu of htmlArea (extension: sr_htmlarea)
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'Cut' => 'Cut',
		'Copy' => 'Copy',
		'Paste' => 'Paste',
		'Image Properties' => '_Image Properties...',
		'Modify Link' => '_Modify Link...',
		'Check Link' => 'Chec_k Link...',
		'Remove Link' => '_Remove Link...',
		'Cell Properties' => 'C_ell Properties...',
		'Row Properties' => 'Ro_w Properties...',
		'Insert Row Before' => 'I_nsert Row Before',
		'Insert Row After' => 'In_sert Row After',
		'Delete Row' => '_Delete Row',
		'Table Properties' => '_Table Properties...',
		'Insert Column Before' => 'Insert _Column Before',
		'Insert Column After' => 'Insert C_olumn After',
		'Delete Column' => 'De_lete Column',
		'Justify Left' => 'Justify Left',
		'Justify Center' => 'Justify Center',
		'Justify Right' => 'Justify Right',
		'Justify Full' => 'Justify Full',
		'Make link' => 'Make lin_k...',
		'Remove the' => 'Remove the',
		'Element' => 'Element...',
		'Please confirm that you want to remove this element:' => 'Please confirm that you want to remove this element:',
		'Remove this node from the document' => 'Remove this node from the document',
		'How did you get here? (Please report!)' => 'How did you get here? (Please report!)',
		'Show the image properties dialog' => 'Show the image properties dialog',
		'Modify URL' => 'Modify URL',
		'Current URL is' => 'Current URL is',
		'Opens this link in a new window' => 'Opens this link in a new window',
		'Please confirm that you want to unlink this element.' => 'Please confirm that you want to unlink this element.',
		'Link points to:' => 'Link points to:',
		'Unlink the current element' => 'Unlink the current element',
		'Show the Table Cell Properties dialog' => 'Show the Table Cell Properties dialog',
		'Show the Table Row Properties dialog' => 'Show the Table Row Properties dialog',
		'Insert a new row before the current one' => 'Insert a new row before the current one',
		'Insert a new row after the current one' => 'Insert a new row after the current one',
		'Delete the current row' => 'Delete the current row',
		'Show the Table Properties dialog' => 'Show the Table Properties dialog',
		'Insert a new column before the current one' => 'Insert a new column before the current one',
		'Insert a new column after the current one' => 'Insert a new column after the current one',
		'Delete the current column' => 'Delete the current column',
		'Create a link' => 'Create a link',
		'Insert paragraph before' => 'Insert paragraph before',
		'Insert a paragraph before the current node' => 'Insert a paragraph before the current node',
		'Insert paragraph after' => 'Insert paragraph after',
		'Insert a paragraph after the current node' => 'Insert a paragraph after the current node',
	),
	'dk' => Array (
	),
	'de' => Array (
		'Cut' => 'Ausschneiden',
		'Copy' => 'Kopieren',
		'Paste' => 'Einfügen',
		'Image Properties' => '_Bildeigenschaften...',
		'Modify Link' => '_Link ändern...',
		'Check Link' => 'Lin_k prüfen...',
		'Remove Link' => 'Link entfe_rnen...',
		'Cell Properties' => 'Z_elleigenschaften...',
		'Row Properties' => 'S_palteneigenschaften...',
		'Insert Row Before' => 'Zeile ei_nfügen vor',
		'Insert Row After' => 'Zeile ein_fügen nach',
		'Delete Row' => 'Zeile lö_schen',
		'Table Properties' => '_Tabelleneigenschaften...',
		'Insert Column Before' => 'Sp_alte einfügen vor',
		'Insert Column After' => 'Spalte einfü_gen nach',
		'Delete Column' => 'Spalte _löschen',
		'Justify Left' => 'Links',
		'Justify Center' => 'Zentriert',
		'Justify Right' => 'Rechts',
		'Justify Full' => 'Blocksatz',
		'Make link' => 'Llin_k erzeugen...',
		'Remove the' => 'Entferne das',
		'Element' => 'Element...',
		'Please confirm that you want to remove this element:' => 'Bitte bestätigen Sie, dass Sie dieses Element entfernen möchten:',
		'Remove this node from the document' => 'Entferne diesen Teil aus dem Dokument',
		'How did you get here? (Please report!)' => 'Wie gelangten Sie hierher? (Bitte berichten!)',
		'Show the image properties dialog' => 'Zeigt den Bildeigenschaftsdialog',
		'Modify URL' => 'URL ändern',
		'Current URL is' => 'Die momentane URL ist',
		'Opens this link in a new window' => 'Öffnet diesen Link in einem neuen Fenster',
		'Please confirm that you want to unlink this element.' => 'Bitte bestätigen Sie, dass Sie diesen Link entfernen möchten',
		'Link points to:' => 'Der Link weist auf:',
		'Unlink the current element' => 'Den aktuellen Link entfernen',
		'Show the Table Cell Properties dialog' => 'Zeigt den Zelleigenschafts-Dialog der Tabelle',
		'Show the Table Row Properties dialog' => 'Zeigt den Zeileneigenschafts-Dialog der Tabelle',
		'Insert a new row before the current one' => 'Fügt eine neue Zeile vor der aktuellen ein',
		'Insert a new row after the current one' => 'Fügt eine neue Zeile nach der aktuellen ein',
		'Delete the current row' => 'Löscht die aktuelle Zeile',
		'Show the Table Properties dialog' => 'Zeigt den Tabelleneigenschafts-Dialog',
		'Insert a new column before the current one' => 'Fügt eine neue Spalte vor der aktuellen ein',
		'Insert a new column after the current one' => 'Fügt eine neue Spalte nach der aktuellen ein',
		'Delete the current column' => 'Löscht die aktuelle Spalte',
		'Create a link' => 'Link erzeugen',
		'Insert paragraph before' => 'Fügt einen Absatz vor diesem ein',
		'Insert a paragraph before the current node' => 'Fügt einen Absatz vor dem aktuellen Knotenpunkt ein',
		'Insert paragraph after' => 'Fügt einen Absatz nach diesem ein',
		'Insert a paragraph after the current node' => 'Fügt einen Absatz vor dem aktuellen Knotenpunkt ein',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
		'Cut' => 'Couper',
		'Copy' => 'Copier',
		'Paste' => 'Coller',
		'Image Properties' => 'Propriétés de l\'_image',
		'Modify Link' => '_Modifier le l_ien',
		'Check Link' => '_Vérifier le lien',
		'Remove Link' => 'Supprimer le li_en',
		'Cell Properties' => 'Propriétés de la cell_ule',
		'Row Properties' => 'Propriétés de la ran_gée',
		'Insert Row Before' => 'Insérer une _rangée avant',
		'Insert Row After' => 'Insérer une r_angée après',
		'Delete Row' => 'Supprimer la rangé_e',
		'Table Properties' => 'Propriétés de la _table',
		'Insert Column Before' => 'Insérer une _colonne avant',
		'Insert Column After' => 'Insérer une c_olonne après',
		'Delete Column' => 'Supprimer la colo_nne',
		'Justify Left' => 'Justifié à  gauche',
		'Justify Center' => 'Centré',
		'Justify Right' => 'Justifié à  droite',
		'Justify Full' => 'Justifié à  gauche et à  droite',
		'Make link' => 'Insérer un _lien',
		'Remove the' => 'Supprimer l\'élément ',
		'Element' => ' ',
		'Please confirm that you want to remove this element:' => 'Veuillez confirmer que vous désirez supprimer cet élément:',
		'Remove this node from the document' => 'Retirer ce noeud du document',
		'How did you get here? (Please report!)' => 'Comment êtes-vous arrivé ici? (Veuillez signaler ce problème!)',
		'Show the image properties dialog' => 'Présenter les propriétés de l\'image',
		'Modify URL' => 'Modifier l\'URL',
		'Current URL is' => 'L\'URL courante est',
		'Opens this link in a new window' => 'Ouvrir ce lien dans une nouvelle fenêtre',
		'Please confirm that you want to unlink this element.' => 'Veuillez confirmer que vous désirez supprimer ce lien.',
		'Link points to:' => 'Le lien pointe à :',
		'Unlink the current element' => 'Supprimer le lien',
		'Show the Table Cell Properties dialog' => 'Présenter les propriétés de la cellule',
		'Show the Table Row Properties dialog' => 'Présenter les propriétés de la rangée de table',
		'Insert a new row before the current one' => 'Insérer une rangée avant la rangée courante',
		'Insert a new row after the current one' => 'Insérer une rangée après la rangée courante',
		'Delete the current row' => 'Supprimer la colonne courante',
		'Show the Table Properties dialog' => 'Présenter les propriétés de la table',
		'Insert a new column before the current one' => 'Insérer une colonne avant la colonne courante',
		'Insert a new column after the current one' => 'Insérer une colonne après la colonne courante',
		'Delete the current column' => 'Supprimer la colonne courante',
		'Create a link' => 'Insérer un lien',
		'Insert paragraph before' => 'Insérer un paragraphe avant',
		'Insert a paragraph before the current node' => 'Insérer un paragraphe avant le noeud courant',
		'Insert paragraph after' => 'Insérer un paragraphe après',
		'Insert a paragraph after the current node' => 'Insérer un paragraphe après le noeud courant',
	),
	'es' => Array (
		'Cut' => 'Cortar',
		'Copy' => 'Copiar',
		'Paste' => 'Pegar',
		'Image Properties' => 'Propriedades de la imagen...',
		'Modify Link' => 'Cambiar el enlace...',
		'Check Link' => 'Comprobar el enlace...',
		'Remove Link' => 'Borrar el enlace...',
		'Cell Properties' => 'Propriedades de la celda...',
		'Row Properties' => 'Propriedades de la _fila...',
		'Insert Row Before' => 'Insertar fila encima',
		'Insert Row After' => 'Insertar fila debajo',
		'Delete Row' => 'Borrar fila',
		'Table Properties' => 'Propriedades de la _tabla...',
		'Insert Column Before' => 'Insertar columna delante',
		'Insert Column After' => 'Insertar columna detrás',
		'Delete Column' => 'Borrar columna',
		'Justify Left' => 'Alinear a la izquierda',
		'Justify Center' => 'Centrar',
		'Justify Right' => 'Alinear a la derecha',
		'Justify Full' => 'Justificar',
		'Make link' => 'Insertar en_lace...',
		'Remove the' => 'Borrar el elemento ',
		'Element' => ' ',
		'Please confirm that you want to remove this element:' => '¿Está seguro que desea borrar este elemento?',
		'Remove this node from the document' => 'Borra el nudo del documento',
		'How did you get here? (Please report!)' => '¿Cómo llegó usted aquí­? (Gracia de informarnos!)',
		'Show the image properties dialog' => 'Abre ventana para ver o editar las propriedades de la imagen',
		'Modify URL' => 'Cambia el enlace',
		'Current URL is' => 'El enlace actual llega a:',
		'Opens this link in a new window' => 'Abre el enlace en nueva ventana',
		'Please confirm that you want to unlink this element.' => '¿Está seguro que desea borrar este enlace?',
		'Link points to:' => 'El enlace actual llega a',
		'Unlink the current element' => 'Borra el enlace',
		'Show the Table Cell Properties dialog' => 'Abre una ventana para ver o editar las propriedades de la celda seleccionada',
		'Show the Table Row Properties dialog' => 'Abre una ventana para ver o editar las propriedades de la fila seleccionada',
		'Insert a new row before the current one' => 'Inserta una fila encima la fila seleccionada',
		'Insert a new row after the current one' => 'Inserta una fila debajo la fila seleccionada',
		'Delete the current row' => 'Borra la fila seleccionada',
		'Show the Table Properties dialog' => 'Abre una ventana para ver o editar las propriedades de la tabla seleccionada',
		'Insert a new column before the current one' => 'Inserta una columna delante la columna seleccionada',
		'Insert a new column after the current one' => 'Inserta una columna detrás la columna seleccionada',
		'Delete the current column' => 'Borra la columna seleccionada',
		'Create a link' => 'Inserta un enlace',
		'Insert paragraph before' => 'Insertar párrafo delante',
		'Insert a paragraph before the current node' => 'Insertar párrafo delante el nudo corriente',
		'Insert paragraph after' => 'Insertar párrafo detrás',
		'Insert a paragraph after the current node' => 'Insertar párrafo detrás el nudo corriente',
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'Cut' => 'Leikkaa',
		'Copy' => 'Kopioi',
		'Paste' => 'Liitä',
		'Image Properties' => '_Kuva ominaisuudet...',
		'Modify Link' => '_Muuta linkki...',
		'Check Link' => 'Tarkista _linkki...',
		'Remove Link' => '_Poista linkki...',
		'Cell Properties' => '_Solun ominaisuudet...',
		'Row Properties' => 'Rivin _ominaisuudet...',
		'Insert Row Before' => 'Lisää rivi _eteen...',
		'Insert Row After' => 'Lisää rivi _taakse...',
		'Delete Row' => '_Poista rivi...',
		'Table Properties' => '_Taulun ominaisuudet',
		'Insert Column Before' => 'Lisää _sarake eteen',
		'Insert Column After' => 'Lisää s_arake taakse',
		'Delete Column' => 'Poista sara_ke...',
		'Justify Left' => 'Tasaa vasemmalle',
		'Justify Center' => 'Tasaa keskelle',
		'Justify Right' => 'Tasaa oikealle',
		'Justify Full' => 'Tasaa koko alueelle',
		'Make link' => 'Tee l_inkki...',
		'Remove the' => 'Poista',
		'Element' => 'Elementti...',
		'Please confirm that you want to remove this element:' => 'Ole hyvä ja vahvista että haluat poistaa tämän elementin:',
		'Remove this node from the document' => 'Poista tämä yhteys asiakirjasta.',
		'How did you get here? (Please report!)' => 'Kuinka pääsit tänne? Ole hyvä ja raportoi!',
		'Show the image properties dialog' => 'Näytä kuvan ominaisuuksien dialogi',
		'Modify URL' => 'Muuta URLia',
		'Current URL is' => 'Nykyinen URL on',
		'Opens this link in a new window' => 'Avaa tämä linkki uudessa ikkunassa',
		'Please confirm that you want to unlink this element.' => 'Ole hyvä ja vahvista että haluat poistaa linkin tästä elementistä.',
		'Link points to:' => 'Linkki osoittaa:',
		'Unlink the current element' => 'Poista linkki nykyisestä elementistä',
		'Show the Table Cell Properties dialog' => 'Näytä taulukon solujen ominaisuuksien dialogi',
		'Show the Table Row Properties dialog' => 'Näytä taulukon rivien ominaisuuksien dialogi',
		'Insert a new row before the current one' => 'Lisää uusi rivi nykyisen eteen',
		'Insert a new row after the current one' => 'Lisää uusi rivi nykyisen taakse',
		'Delete the current row' => 'Poista nykyinen rivi',
		'Show the Table Properties dialog' => 'Näytä taulukon ominaisuuksien rivi',
		'Insert a new column before the current one' => 'Lisää uusi sarake nykyisen eteen',
		'Insert a new column after the current one' => 'Lisää uusi sarake nykyisen taakse',
		'Delete the current column' => 'Poista nykyinen sarake',
		'Create a link' => 'Luo linkki',
		'Insert paragraph before' => 'Lisää kappale eteen',
		'Insert a paragraph before the current node' => 'Lisää kappale eteen nykyisellä asetuksella',
		'Insert paragraph after' => 'Lisää kappale jälkeen',
		'Insert a paragraph after the current node' => 'Lisää kappale jälkeen nykyisellä asetuksella',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>