<?php
/**
 * Language labels for plugin ContextMenu of htmlArea (extension: sr_htmlarea)
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'Cut' => 'Cut',
		'Copy' => 'Copy',
		'Paste' => 'Paste',
		'Image Properties' => '_Image Properties...',
		'Modify Link' => '_Modify Link...',
		'Check Link' => 'Chec_k Link...',
		'Remove Link' => '_Remove Link...',
		'Cell Properties' => 'C_ell Properties...',
		'Row Properties' => 'Ro_w Properties...',
		'Insert Row Before' => 'I_nsert Row Before',
		'Insert Row After' => 'In_sert Row After',
		'Delete Row' => '_Delete Row',
		'Table Properties' => '_Table Properties...',
		'Insert Column Before' => 'Insert _Column Before',
		'Insert Column After' => 'Insert C_olumn After',
		'Delete Column' => 'De_lete Column',
		'Justify Left' => 'Justify Left',
		'Justify Center' => 'Justify Center',
		'Justify Right' => 'Justify Right',
		'Justify Full' => 'Justify Full',
		'Make link' => 'Make lin_k...',
		'Remove the' => 'Remove the',
		'Element' => 'Element...',
		'Please confirm that you want to remove this element:' => 'Please confirm that you want to remove this element:',
		'Remove this node from the document' => 'Remove this node from the document',
		'How did you get here? (Please report!)' => 'How did you get here? (Please report!)',
		'Show the image properties dialog' => 'Show the image properties dialog',
		'Modify URL' => 'Modify URL',
		'Current URL is' => 'Current URL is',
		'Opens this link in a new window' => 'Opens this link in a new window',
		'Please confirm that you want to unlink this element.' => 'Please confirm that you want to unlink this element.',
		'Link points to:' => 'Link points to:',
		'Unlink the current element' => 'Unlink the current element',
		'Show the Table Cell Properties dialog' => 'Show the Table Cell Properties dialog',
		'Show the Table Row Properties dialog' => 'Show the Table Row Properties dialog',
		'Insert a new row before the current one' => 'Insert a new row before the current one',
		'Insert a new row after the current one' => 'Insert a new row after the current one',
		'Delete the current row' => 'Delete the current row',
		'Show the Table Properties dialog' => 'Show the Table Properties dialog',
		'Insert a new column before the current one' => 'Insert a new column before the current one',
		'Insert a new column after the current one' => 'Insert a new column after the current one',
		'Delete the current column' => 'Delete the current column',
		'Create a link' => 'Create a link',
		'Insert paragraph before' => 'Insert paragraph before',
		'Insert a paragraph before the current node' => 'Insert a paragraph before the current node',
		'Insert paragraph after' => 'Insert paragraph after',
		'Insert a paragraph after the current node' => 'Insert a paragraph after the current node',
	),
	'dk' => Array (
	),
	'de' => Array (
		'Cut' => 'Ausschneiden',
		'Copy' => 'Kopieren',
		'Paste' => 'Einfьgen',
		'Image Properties' => '_Bildeigenschaften...',
		'Modify Link' => '_Link дndern...',
		'Check Link' => 'Lin_k prьfen...',
		'Remove Link' => 'Link entfe_rnen...',
		'Cell Properties' => 'Z_elleigenschaften...',
		'Row Properties' => '_Zeileneigenschaften...',
		'Insert Row Before' => 'Zeile ei_nfьgen vor',
		'Insert Row After' => 'Zeile ein_fьgen nach',
		'Delete Row' => 'Zeile lц_schen',
		'Table Properties' => '_Tabelleneigenschaften...',
		'Insert Column Before' => 'Sp_alte einfьgen vor',
		'Insert Column After' => 'Spalte einfь_gen nach',
		'Delete Column' => 'Spalte _lцschen',
		'Justify Left' => 'Links',
		'Justify Center' => 'Zentriert',
		'Justify Right' => 'Rechts',
		'Justify Full' => 'Blocksatz',
		'Make link' => 'Lin_k erzeugen...',
		'Remove the' => 'Entferne das',
		'Element' => 'Element...',
		'Please confirm that you want to remove this element:' => 'Bitte bestдtigen Sie, dass Sie dieses Element entfernen mцchten:',
		'Remove this node from the document' => 'Entferne diesen Teil aus dem Dokument',
		'How did you get here? (Please report!)' => 'Wie gelangten Sie hierher? (Bitte berichten!)',
		'Show the image properties dialog' => 'Zeigt den Bildeigenschaftsdialog',
		'Modify URL' => 'URL дndern',
		'Current URL is' => 'Die momentane URL ist',
		'Opens this link in a new window' => 'Цffnet diesen Link in einem neuen Fenster',
		'Please confirm that you want to unlink this element.' => 'Bitte bestдtigen Sie, dass Sie diesen Link entfernen mцchten',
		'Link points to:' => 'Der Link zeigt auf:',
		'Unlink the current element' => 'Den aktuellen Link entfernen',
		'Show the Table Cell Properties dialog' => 'Zeigt den Zelleigenschafts-Dialog der Tabelle',
		'Show the Table Row Properties dialog' => 'Zeigt den Zeileneigenschafts-Dialog der Tabelle',
		'Insert a new row before the current one' => 'Fьgt eine neue Zeile vor der aktuellen ein',
		'Insert a new row after the current one' => 'Fьgt eine neue Zeile nach der aktuellen ein',
		'Delete the current row' => 'Lцscht die aktuelle Zeile',
		'Show the Table Properties dialog' => 'Zeigt den Tabelleneigenschafts-Dialog',
		'Insert a new column before the current one' => 'Fьgt eine neue Spalte vor der aktuellen ein',
		'Insert a new column after the current one' => 'Fьgt eine neue Spalte nach der aktuellen ein',
		'Delete the current column' => 'Lцscht die aktuelle Spalte',
		'Create a link' => 'Link erzeugen',
		'Insert paragraph before' => 'Fьgt einen Absatz vor diesem ein',
		'Insert a paragraph before the current node' => 'Fьgt einen Absatz vor dem aktuellen Knotenpunkt ein',
		'Insert paragraph after' => 'Fьgt einen Absatz nach diesem ein',
		'Insert a paragraph after the current node' => 'Fьgt einen Absatz vor dem aktuellen Knotenpunkt ein',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
		'Cut' => 'Couper',
		'Copy' => 'Copier',
		'Paste' => 'Coller',
		'Image Properties' => 'Propriйtйs de l\'_image',
		'Modify Link' => '_Modifier le l_ien',
		'Check Link' => '_Vйrifier le lien',
		'Remove Link' => 'Supprimer le li_en',
		'Cell Properties' => 'Propriйtйs de la cell_ule',
		'Row Properties' => 'Propriйtйs de la ran_gйe',
		'Insert Row Before' => 'Insйrer une _rangйe avant',
		'Insert Row After' => 'Insйrer une r_angйe aprиs',
		'Delete Row' => 'Supprimer la rangй_e',
		'Table Properties' => 'Propriйtйs de la _table',
		'Insert Column Before' => 'Insйrer une _colonne avant',
		'Insert Column After' => 'Insйrer une c_olonne aprиs',
		'Delete Column' => 'Supprimer la colo_nne',
		'Justify Left' => 'Justifiй а  gauche',
		'Justify Center' => 'Centrй',
		'Justify Right' => 'Justifiй а  droite',
		'Justify Full' => 'Justifiй а  gauche et а  droite',
		'Make link' => 'Insйrer un _lien',
		'Remove the' => 'Supprimer l\'йlйment ',
		'Element' => ' ',
		'Please confirm that you want to remove this element:' => 'Veuillez confirmer que vous dйsirez supprimer cet йlйment:',
		'Remove this node from the document' => 'Retirer ce noeud du document',
		'How did you get here? (Please report!)' => 'Comment кtes-vous arrivй ici? (Veuillez signaler ce problиme!)',
		'Show the image properties dialog' => 'Prйsenter les propriйtйs de l\'image',
		'Modify URL' => 'Modifier l\'URL',
		'Current URL is' => 'L\'URL courante est',
		'Opens this link in a new window' => 'Ouvrir ce lien dans une nouvelle fenкtre',
		'Please confirm that you want to unlink this element.' => 'Veuillez confirmer que vous dйsirez supprimer ce lien.',
		'Link points to:' => 'Le lien pointe а :',
		'Unlink the current element' => 'Supprimer le lien',
		'Show the Table Cell Properties dialog' => 'Prйsenter les propriйtйs de la cellule',
		'Show the Table Row Properties dialog' => 'Prйsenter les propriйtйs de la rangйe de table',
		'Insert a new row before the current one' => 'Insйrer une rangйe avant la rangйe courante',
		'Insert a new row after the current one' => 'Insйrer une rangйe aprиs la rangйe courante',
		'Delete the current row' => 'Supprimer la colonne courante',
		'Show the Table Properties dialog' => 'Prйsenter les propriйtйs de la table',
		'Insert a new column before the current one' => 'Insйrer une colonne avant la colonne courante',
		'Insert a new column after the current one' => 'Insйrer une colonne aprиs la colonne courante',
		'Delete the current column' => 'Supprimer la colonne courante',
		'Create a link' => 'Insйrer un lien',
		'Insert paragraph before' => 'Insйrer un paragraphe avant',
		'Insert a paragraph before the current node' => 'Insйrer un paragraphe avant le noeud courant',
		'Insert paragraph after' => 'Insйrer un paragraphe aprиs',
		'Insert a paragraph after the current node' => 'Insйrer un paragraphe aprиs le noeud courant',
	),
	'es' => Array (
		'Cut' => 'Cortar',
		'Copy' => 'Copiar',
		'Paste' => 'Pegar',
		'Image Properties' => 'Propriedades de la imagen...',
		'Modify Link' => 'Cambiar el enlace...',
		'Check Link' => 'Comprobar el enlace...',
		'Remove Link' => 'Borrar el enlace...',
		'Cell Properties' => 'Propriedades de la celda...',
		'Row Properties' => 'Propriedades de la _fila...',
		'Insert Row Before' => 'Insertar fila encima',
		'Insert Row After' => 'Insertar fila debajo',
		'Delete Row' => 'Borrar fila',
		'Table Properties' => 'Propriedades de la _tabla...',
		'Insert Column Before' => 'Insertar columna delante',
		'Insert Column After' => 'Insertar columna detrбs',
		'Delete Column' => 'Borrar columna',
		'Justify Left' => 'Alinear a la izquierda',
		'Justify Center' => 'Centrar',
		'Justify Right' => 'Alinear a la derecha',
		'Justify Full' => 'Justificar',
		'Make link' => 'Insertar en_lace...',
		'Remove the' => 'Borrar el elemento ',
		'Element' => ' ',
		'Please confirm that you want to remove this element:' => 'їEstб seguro que desea borrar este elemento?',
		'Remove this node from the document' => 'Borra el nudo del documento',
		'How did you get here? (Please report!)' => 'їCуmo llegу usted aquн­? (Gracia de informarnos!)',
		'Show the image properties dialog' => 'Abre ventana para ver o editar las propriedades de la imagen',
		'Modify URL' => 'Cambia el enlace',
		'Current URL is' => 'El enlace actual llega a:',
		'Opens this link in a new window' => 'Abre el enlace en nueva ventana',
		'Please confirm that you want to unlink this element.' => 'їEstб seguro que desea borrar este enlace?',
		'Link points to:' => 'El enlace actual llega a',
		'Unlink the current element' => 'Borra el enlace',
		'Show the Table Cell Properties dialog' => 'Abre una ventana para ver o editar las propriedades de la celda seleccionada',
		'Show the Table Row Properties dialog' => 'Abre una ventana para ver o editar las propriedades de la fila seleccionada',
		'Insert a new row before the current one' => 'Inserta una fila encima la fila seleccionada',
		'Insert a new row after the current one' => 'Inserta una fila debajo la fila seleccionada',
		'Delete the current row' => 'Borra la fila seleccionada',
		'Show the Table Properties dialog' => 'Abre una ventana para ver o editar las propriedades de la tabla seleccionada',
		'Insert a new column before the current one' => 'Inserta una columna delante la columna seleccionada',
		'Insert a new column after the current one' => 'Inserta una columna detrбs la columna seleccionada',
		'Delete the current column' => 'Borra la columna seleccionada',
		'Create a link' => 'Inserta un enlace',
		'Insert paragraph before' => 'Insertar pбrrafo delante',
		'Insert a paragraph before the current node' => 'Insertar pбrrafo delante el nudo corriente',
		'Insert paragraph after' => 'Insertar pбrrafo detrбs',
		'Insert a paragraph after the current node' => 'Insertar pбrrafo detrбs el nudo corriente',
	),
	'nl' => Array (
		'Cut' => 'Knip',
		'Copy' => 'Kopieer',
		'Paste' => 'Plak',
		'Image Properties' => '_Eigenschappen afbeelding...',
		'Modify Link' => '_Link aanpassen...',
		'Check Link' => 'Controlee_r Link...',
		'Remove Link' => '-Verwijder Link...',
		'Cell Properties' => 'C_eleigenschappen...',
		'Row Properties' => 'R_ij-eigenschappen',
		'Insert Row Before' => 'I_nvoegen Rij Voor',
		'Insert Row After' => 'In_voegen Rij Na',
		'Delete Row' => '_Verwijder Rij',
		'Table Properties' => '_Tabeleigenschappen...',
		'Insert Column Before' => 'Invoegen_Kolom Voor',
		'Insert Column After' => 'Invoegen_Kolom Na',
		'Delete Column' => 'Ve_rwijder Kolom',
		'Justify Left' => 'Links uitvullen',
		'Justify Center' => 'Gecentreerd uitvullen',
		'Justify Right' => 'Rechts uitvullen',
		'Justify Full' => 'Volledig uitvullen',
		'Make link' => 'Maak lin_k...',
		'Remove the' => 'Verwijder de',
		'Element' => 'Element...',
		'Please confirm that you want to remove this element:' => 'Bevestig aub dat u dit element wilt verwijderen',
		'Remove this node from the document' => 'Verwijder dit knooppunt uit het document',
		'How did you get here? (Please report!)' => 'Hoe kwam u hier terecht?',
		'Show the image properties dialog' => 'Toon afbeeldingseigenschappen',
		'Modify URL' => 'Pas URL aan',
		'Current URL is' => 'Huidige URL is',
		'Opens this link in a new window' => 'Opent deze link in een nieuw venster',
		'Please confirm that you want to unlink this element.' => 'Bevestig aub dat u dit element wilt ontdoen van een link',
		'Link points to:' => 'Link verwijst naar:',
		'Unlink the current element' => 'Verwijder link van huidig element',
		'Show the Table Cell Properties dialog' => 'Toon de eigenschappen van de cel in de tabel',
		'Show the Table Row Properties dialog' => 'Toon de eigenschappen van de rij in de tabel',
		'Insert a new row before the current one' => 'Voeg een nieuwe rij in voor de huidige',
		'Insert a new row after the current one' => 'Voeg een nieuwe rij in na de huidige',
		'Delete the current row' => 'Verwijder de huidige rij',
		'Show the Table Properties dialog' => 'Toon de eigenschappen van de tabel',
		'Insert a new column before the current one' => 'Voeg een nieuwe kolom in voor de huidige',
		'Insert a new column after the current one' => 'Voeg een nieuwe kolom in na de huidige',
		'Delete the current column' => 'Verwijder de huidige kolom',
		'Create a link' => 'Maak een link',
		'Insert paragraph before' => 'Voeg hiervoor een alinea in',
		'Insert a paragraph before the current node' => 'Voeg een alinea in voor het huidige knooppunt',
		'Insert paragraph after' => 'Voeg hierna een alinea in',
		'Insert a paragraph after the current node' => 'Voeg een alinea in na het huidige knooppunt',
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'Cut' => 'Leikkaa',
		'Copy' => 'Kopioi',
		'Paste' => 'Liitд',
		'Image Properties' => '_Kuva ominaisuudet...',
		'Modify Link' => '_Muuta linkki...',
		'Check Link' => 'Tarkista _linkki...',
		'Remove Link' => '_Poista linkki...',
		'Cell Properties' => '_Solun ominaisuudet...',
		'Row Properties' => 'Rivin _ominaisuudet...',
		'Insert Row Before' => 'Lisдд rivi _eteen...',
		'Insert Row After' => 'Lisдд rivi _taakse...',
		'Delete Row' => '_Poista rivi...',
		'Table Properties' => '_Taulun ominaisuudet',
		'Insert Column Before' => 'Lisдд _sarake eteen',
		'Insert Column After' => 'Lisдд s_arake taakse',
		'Delete Column' => 'Poista sara_ke...',
		'Justify Left' => 'Tasaa vasemmalle',
		'Justify Center' => 'Tasaa keskelle',
		'Justify Right' => 'Tasaa oikealle',
		'Justify Full' => 'Tasaa koko alueelle',
		'Make link' => 'Tee l_inkki...',
		'Remove the' => 'Poista',
		'Element' => 'Elementti...',
		'Please confirm that you want to remove this element:' => 'Ole hyvд ja vahvista ettд haluat poistaa tдmдn elementin:',
		'Remove this node from the document' => 'Poista tдmд yhteys asiakirjasta.',
		'How did you get here? (Please report!)' => 'Kuinka pддsit tдnne? Ole hyvд ja raportoi!',
		'Show the image properties dialog' => 'Nдytд kuvan ominaisuuksien dialogi',
		'Modify URL' => 'Muuta URLia',
		'Current URL is' => 'Nykyinen URL on',
		'Opens this link in a new window' => 'Avaa tдmд linkki uudessa ikkunassa',
		'Please confirm that you want to unlink this element.' => 'Ole hyvд ja vahvista ettд haluat poistaa linkin tдstд elementistд.',
		'Link points to:' => 'Linkki osoittaa:',
		'Unlink the current element' => 'Poista linkki nykyisestд elementistд',
		'Show the Table Cell Properties dialog' => 'Nдytд taulukon solujen ominaisuuksien dialogi',
		'Show the Table Row Properties dialog' => 'Nдytд taulukon rivien ominaisuuksien dialogi',
		'Insert a new row before the current one' => 'Lisдд uusi rivi nykyisen eteen',
		'Insert a new row after the current one' => 'Lisдд uusi rivi nykyisen taakse',
		'Delete the current row' => 'Poista nykyinen rivi',
		'Show the Table Properties dialog' => 'Nдytд taulukon ominaisuuksien rivi',
		'Insert a new column before the current one' => 'Lisдд uusi sarake nykyisen eteen',
		'Insert a new column after the current one' => 'Lisдд uusi sarake nykyisen taakse',
		'Delete the current column' => 'Poista nykyinen sarake',
		'Create a link' => 'Luo linkki',
		'Insert paragraph before' => 'Lisдд kappale eteen',
		'Insert a paragraph before the current node' => 'Lisдд kappale eteen nykyisellд asetuksella',
		'Insert paragraph after' => 'Lisдд kappale jдlkeen',
		'Insert a paragraph after the current node' => 'Lisдд kappale jдlkeen nykyisellд asetuksella',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
		'Cut' => 'Вырезать',
		'Copy' => 'Копировать',
		'Paste' => 'Вставить',
		'Image Properties' => 'Свойства картинки...',
		'Modify Link' => 'Изменить ссылку...',
		'Check Link' => 'Проверить ссылку...',
		'Remove Link' => 'Удалить ссылку...',
		'Cell Properties' => 'Свойства ячейки...',
		'Row Properties' => 'Свойства строки...',
		'Insert Row Before' => 'Вставить строку выше',
		'Insert Row After' => 'Вставить строку ниже',
		'Delete Row' => 'Удалить строку',
		'Table Properties' => 'Свойства таблицы',
		'Insert Column Before' => 'Вставить колонку слева',
		'Insert Column After' => 'Вставить колонку справа',
		'Delete Column' => 'Удалить колонку',
		'Justify Left' => 'Выравнивать по левому краю',
		'Justify Center' => 'Выравнивать по центру',
		'Justify Right' => 'Выравнивать по правому краю',
		'Justify Full' => 'Выравнивать по обоим краям',
		'Make link' => 'Создать ссылку...',
		'Remove the' => 'Удалить',
		'Element' => 'Эелемент...',
		'Please confirm that you want to remove this element:' => 'Пожалуйста подтвердите, что Вы хотите удалить этот элемент:',
		'Remove this node from the document' => 'Удалить этот элемент с подэлементами из документа',
		'How did you get here? (Please report!)' => 'Как это Вы сюда попали? Пожалуйста, сообщите разработчикам об этом!',
		'Show the image properties dialog' => 'Показать окно свойств изображения',
		'Modify URL' => 'Изменить адрес',
		'Current URL is' => 'Текущий адрес:',
		'Opens this link in a new window' => 'Открывает ссылку в новом окне',
		'Please confirm that you want to unlink this element.' => 'Пожалуйста подтвердите, что Вы хотите удалить ссылку с этого элемент',
		'Link points to:' => 'Ссылка указывает на:',
		'Unlink the current element' => 'Удалить ссылку с этого элемента',
		'Show the Table Cell Properties dialog' => 'Показать окно свойств ячеек таблицы',
		'Show the Table Row Properties dialog' => 'Показать окно свойств строк таблицы',
		'Insert a new row before the current one' => 'Вставить новую строку перед текущей',
		'Insert a new row after the current one' => 'Вставить новую строку после текущей',
		'Delete the current row' => 'Удалить текущую строку',
		'Show the Table Properties dialog' => 'Показать окно свойств таблицы',
		'Insert a new column before the current one' => 'Вставить колонку перед текущей',
		'Insert a new column after the current one' => 'Вставить колонку после текущей',
		'Delete the current column' => 'Удалить текущую колонку',
		'Create a link' => 'Создать ссылку',
		'Insert paragraph before' => 'Вставить параграф выше',
		'Insert a paragraph before the current node' => 'Вставить параграф перед текущим элементом',
		'Insert paragraph after' => 'Вставить параграф ниже',
		'Insert a paragraph after the current node' => 'Вставить параграф после текущего элемента',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>