<?php
/**
 * Language labels for plugin TableOperations of RTE HtmalArea (extension: rte_pb_htmlarea)
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'Align' => 'Align',
		'All four sides' => 'All four sides',
		'Background' => 'Background',
		'Baseline' => 'Baseline',
		'Border' => 'Border',
		'Borders' => 'Borders',
		'Bottom' => 'Bottom',
		'CSS Style' => 'Style [CSS]',
		'Caption' => 'Caption',
		'Cell Properties' => 'Cell Properties',
		'Center' => 'Center',
		'Char' => 'Char',
		'Collapsed borders' => 'Collapsed borders',
		'Color' => 'Color',
		'Description' => 'Description',
		'FG Color' => 'FG Color',
		'Float' => 'Float',
		'Frames' => 'Frames',
		'Height' => 'Height',
		'How many columns would you like to merge?' => 'How many columns would you like to merge?',
		'How many rows would you like to merge?' => 'How many rows would you like to merge?',
		'Image URL' => 'Image URL',
		'Justify' => 'Justify',
		'Layout' => 'Layout',
		'Left' => 'Left',
		'Margin' => 'Margin',
		'Middle' => 'Middle',
		'No rules' => 'No rules',
		'No sides' => 'No sides',
		'None' => 'None',
		'Padding' => 'Padding',
		'Please click into some cell' => 'Please click into some cell',
		'Right' => 'Right',
		'Row Properties' => 'Row Properties',
		'Rules will appear between all rows and columns' => 'Rules will appear between all rows and columns',
		'Rules will appear between columns only' => 'Rules will appear between columns only',
		'Rules will appear between rows only' => 'Rules will appear between rows only',
		'Rules' => 'Rules',
		'Spacing and padding' => 'Spacing and padding',
		'Frame and borders' => 'Frame and borders',
		'Spacing' => 'Spacing',
		'Summary' => 'Summary',
		'TO-cell-delete' => 'Delete cell',
		'TO-cell-insert-after' => 'Insert cell after',
		'TO-cell-insert-before' => 'Insert cell before',
		'TO-cell-merge' => 'Merge cells',
		'TO-cell-prop' => 'Cell properties',
		'TO-cell-split' => 'Split cell',
		'TO-col-delete' => 'Delete column',
		'TO-col-insert-after' => 'Insert column after',
		'TO-col-insert-before' => 'Insert column before',
		'TO-col-split' => 'Split column',
		'TO-row-delete' => 'Delete row',
		'TO-row-insert-above' => 'Insert row before',
		'TO-row-insert-under' => 'Insert row after',
		'TO-row-prop' => 'Row properties',
		'TO-row-split' => 'Split row',
		'TO-table-prop' => 'Table properties',
		'Table Properties' => 'Table Properties',
		'Text align' => 'Text align',
		'The bottom side only' => 'The bottom side only',
		'The left-hand side only' => 'The left-hand side only',
		'The right and left sides only' => 'The right and left sides only',
		'The right-hand side only' => 'The right-hand side only',
		'The top and bottom sides only' => 'The top and bottom sides only',
		'The top side only' => 'The top side only',
		'Top' => 'Top',
		'Unset color' => 'Unset color',
		'Vertical align' => 'Vertical align',
		'Width' => 'Width',
		'not-del-last-cell' => 'HTMLArea cowardly refuses to delete the last cell in row.',
		'not-del-last-col' => 'HTMLArea cowardly refuses to delete the last column in table.',
		'not-del-last-row' => 'HTMLArea cowardly refuses to delete the last row in table.',
		'percent' => 'percent',
		'pixels' => 'pixels',
	),
	'dk' => Array (
	),
	'de' => Array (
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
		'Align' => 'Aligner',
		'All four sides' => 'Les quatre côtés',
		'Background' => 'Arrière-plan',
		'Baseline' => 'Baseline',
		'Border' => 'Bordure',
		'Borders' => 'Épaisseur',
		'Bottom' => 'Bas',
		'CSS Style' => 'Style [CSS]',
		'Caption' => 'Légende',
		'Cell Properties' => 'Propriétés de la cellule',
		'Center' => 'Centré',
		'Char' => 'Caractère',
		'Collapsed borders' => 'Bordures partielles',
		'Color' => 'Couleur',
		'Description' => 'Description',
		'FG Color' => 'Couleur d\'avant-plan',
		'Float' => 'Flottaison',
		'Frames' => 'Cadre',
		'Height' => 'Hauteur',
		'How many columns would you like to merge?' => 'Combien de colonnes désirez-vous fusionner?',
		'How many rows would you like to merge?' => 'Combien de rangées désirez-vous fusionner?',
		'Image URL' => 'URL de l\'image',
		'Justify' => 'Justifié',
		'Layout' => 'Disposition',
		'Left' => 'À gauche',
		'Margin' => 'Marge',
		'Middle' => 'Centre',
		'No rules' => 'Aucune règle',
		'No sides' => 'Aucun côté',
		'None' => 'Aucune',
		'Padding' => 'Dans les cellules',
		'Please click into some cell' => 'Veuillez cliquer dans une cellule',
		'Right' => 'À droite',
		'Row Properties' => 'Propriétés de la rangée',
		'Rules will appear between all rows and columns' => 'Les règles apparaîtront entre toutes les rangées et colonnes',
		'Rules will appear between columns only' => 'Les règles apparaîtront seulement entre les colonnes',
		'Rules will appear between rows only' => 'Les règles apparaîtront seulement entre les rangées',
		'Rules' => 'Règles',
		'Spacing and padding' => 'Espacement',
		'Frame and borders' => 'Cadre et bordures',
		'Spacing' => 'Entre les cellules',
		'Summary' => 'Résumé',
		'TO-cell-delete' => 'Supprimer la cellule',
		'TO-cell-insert-after' => 'Insérer une cellule après',
		'TO-cell-insert-before' => 'Insérer une cellule avant',
		'TO-cell-merge' => 'Fusionner les cellules',
		'TO-cell-prop' => 'Propriétés de la cellule',
		'TO-cell-split' => 'Scinder la cellule',
		'TO-col-delete' => 'Supprimer la colonne',
		'TO-col-insert-after' => 'Insérer une colonne après',
		'TO-col-insert-before' => 'Insérer une colonne avant',
		'TO-col-split' => 'Scinder la colonne',
		'TO-row-delete' => 'Supprimer la rangée',
		'TO-row-insert-above' => 'Insérer une rangée avant',
		'TO-row-insert-under' => 'Insérer une rangée après',
		'TO-row-prop' => 'Propriétés de la rangée',
		'TO-row-split' => 'Scinder la rangée',
		'TO-table-prop' => 'Propriétés de la table',
		'Table Properties' => 'Propriétés de la table',
		'Text align' => 'Alignement du texte',
		'The bottom side only' => 'Le côté en bas seulement',
		'The left-hand side only' => 'Le côté gauche seulement',
		'The right and left sides only' => 'Les côtés droit et gauche seulement',
		'The right-hand side only' => 'Le côté droit seulement',
		'The top and bottom sides only' => 'Les côtés en haut et en bas seulement',
		'The top side only' => 'Le côté en haut seulement',
		'Top' => 'Haut',
		'Unset color' => 'Aucune couleur',
		'Vertical align' => 'Alignement vertical',
		'Width' => 'Largeur',
		'not-del-last-cell' => 'L\'éditeur refuse de supprimer la dernière cellule de la rangée.',
		'not-del-last-col' => 'L\'éditeur refuse de supprimer la dernière colonne de la table.',
		'not-del-last-row' => 'L\'éditeur refuse de supprimer la dernière rangée de la table.',
		'percent' => '%',
		'pixels' => 'pixels',
	),
	'es' => Array (
		'Align' => 'Alinear',
		'All four sides' => 'Los cuatro bordes',
		'Background' => 'Fondo',
		'Baseline' => 'Lí­nea base',
		'Border' => 'Borde',
		'Borders' => 'Bordes',
		'Bottom' => 'Abajo',
		'CSS Style' => 'Estilo [CSS]',
		'Caption' => 'Tí­tulo',
		'Cell Properties' => 'Propiedades de celda',
		'Center' => 'Centrar',
		'Char' => 'Carácter',
		'Collapsed borders' => 'Bordes colapsados',
		'Color' => 'Color',
		'Description' => 'Descripción',
		'FG Color' => 'Color texto',
		'Float' => 'Anclaje',
		'Frames' => 'Marco',
		'Height' => 'Altura',
		'How many columns would you like to merge?' => '¿Cuántas columnas quiere combinar?',
		'How many rows would you like to merge?' => '¿Cuántas filas quiere combinar?',
		'Image URL' => 'URL de la imagen',
		'Justify' => 'Justificar',
		'Layout' => 'Disposición',
		'Left' => 'Izquierda',
		'Margin' => 'Margen',
		'Middle' => 'Al medio',
		'No rules' => 'Sin reglas',
		'No sides' => 'Sin bordes',
		'None' => 'Ninguno',
		'Padding' => 'Acolchado',
		'Please click into some cell' => 'Haga clic en una celda',
		'Right' => 'Derecha',
		'Row Properties' => 'Propiedades de fila',
		'Rules will appear between all rows and columns' => 'Entre todas las filas y columnas',
		'Rules will appear between columns only' => 'Sólo entre las columnas',
		'Rules will appear between rows only' => 'Sólo entre las filas',
		'Rules' => 'Reglas',
		'Spacing and padding' => 'Espaciado y acolchado',
		'Frame and borders' => 'Marco y bordes',
		'Spacing' => 'Espaciado',
		'Summary' => 'Resumen',
		'TO-cell-delete' => 'Borrar celda',
		'TO-cell-insert-after' => 'Insertar celda detrás',
		'TO-cell-insert-before' => 'Insertar celda delante',
		'TO-cell-merge' => 'Combinar celdas',
		'TO-cell-prop' => 'Propiedades de celdas',
		'TO-cell-split' => 'Dividir celda',
		'TO-col-delete' => 'Borrar columna',
		'TO-col-insert-after' => 'Insertar columna detrás',
		'TO-col-insert-before' => 'Insertar columna delante',
		'TO-col-split' => 'Dividir columna',
		'TO-row-delete' => 'Borrar fila',
		'TO-row-insert-above' => 'Insertar fila encima',
		'TO-row-insert-under' => 'Insertar fila debajo',
		'TO-row-prop' => 'Propiedades de fila',
		'TO-row-split' => 'Dividir fila',
		'TO-table-prop' => 'Propiedades de tabla',
		'Table Properties' => 'Propiedades de tabla',
		'Text align' => 'Alinear',
		'The bottom side only' => 'Sólo el borde inferior',
		'The left-hand side only' => 'Sólo el borde izquierdo',
		'The right and left sides only' => 'Sólo los bordes derecho e izquierdo',
		'The right-hand side only' => 'Sólo el borde derecho',
		'The top and bottom sides only' => 'Sólo los bordes superior e inferior',
		'The top side only' => 'Sólo el borde superior',
		'Top' => 'Arriba',
		'Unset color' => 'Eliminar color',
		'Vertical align' => 'Vertical',
		'Width' => 'Anchura',
		'not-del-last-cell' => 'HTMLArea se niega a borrar la última celda de la fila.',
		'not-del-last-col' => 'HTMLArea se niega a borrar la última columna de la tabla.',
		'not-del-last-row' => 'HTMLArea se niega a borrar la última fila de la tabla.',
		'percent' => 'porcentaje',
		'pixels' => 'pí­xeles',
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'Align' => 'Tasaus',
		'All four sides' => 'Kaikilta neljältä puolelta',
		'Background' => 'Tausta',
		'Baseline' => 'Perusviiva',
		'Border' => 'Raja',
		'Borders' => 'Rajat',
		'Bottom' => 'Alas',
		'CSS Style' => 'Tyyli [CSS]',
		'Caption' => 'Kuvateksti',
		'Cell Properties' => 'Solun ominaisuudet',
		'Center' => 'Keskelle',
		'Char' => 'Merkki',
		'Collapsed borders' => 'Kokoonpainuvat rajat',
		'Color' => 'Väri',
		'Description' => 'Kuvaus',
		'FG Color' => 'Edustaväri',
		'Float' => 'Liukuva',
		'Frames' => 'Raamit',
		'Height' => 'Korkeus',
		'How many columns would you like to merge?' => 'Kuinka monta saraketta haluat yhdistää?',
		'How many rows would you like to merge?' => 'Kuinka monta riviä haluat yhdistää?',
		'Image URL' => 'Kuvan URL',
		'Justify' => 'Kohdistus',
		'Layout' => 'Muoto',
		'Left' => 'Vasen',
		'Margin' => 'Marginaali',
		'Middle' => 'Keskellä',
		'No rules' => 'Ei sääntöjä',
		'No sides' => 'Ei puolia',
		'None' => 'Ei mitään',
		'Padding' => 'Täyttö',
		'Please click into some cell' => 'Näpsäytä jotain solua',
		'Right' => 'Oikealle',
		'Row Properties' => 'Rivien ominaisuudet',
		'Rules will appear between all rows and columns' => 'Säännöt käytössä kaikkien rivien ja sarakkeiden välillä.',
		'Rules will appear between columns only' => 'Säännöt käytössä vain sarakkeiden välillä.',
		'Rules will appear between rows only' => 'Säännöt käytössä vain rivien välillä.',
		'Rules' => 'Säännöt',
		'Spacing and padding' => 'Välistys ja täyttö.',
		'Frame and borders' => 'Raamit ja rajat',
		'Spacing' => 'Välistys',
		'Summary' => 'Yhteenveto',
		'TO-cell-delete' => 'Poista solu',
		'TO-cell-insert-after' => 'Lisää solu jälkeen',
		'TO-cell-insert-before' => 'Lisää solu ennen',
		'TO-cell-merge' => 'Yhdistä solut',
		'TO-cell-prop' => 'Solun ominaisuudet',
		'TO-cell-split' => 'Jaa solu',
		'TO-col-delete' => 'Poista sarake',
		'TO-col-insert-after' => 'Lisää sarake jälkeen',
		'TO-col-insert-before' => 'Lisää sarake ennen',
		'TO-col-split' => 'Jaa sarake',
		'TO-row-delete' => 'Poista rivi',
		'TO-row-insert-above' => 'Lisää rivi ennen',
		'TO-row-insert-under' => 'Lisää rivi jälkeen',
		'TO-row-prop' => 'Rivin ominaisuudet',
		'TO-row-split' => 'Jaa rivi',
		'TO-table-prop' => 'Taulukon ominaisuudet',
		'Table Properties' => 'Taulukon ominaisuudet',
		'Text align' => 'Tekstin tasaus',
		'The bottom side only' => 'Ainoastaan alapuoli',
		'The left-hand side only' => 'Ainoastaan vasen puoli',
		'The right and left sides only' => 'Ainoastaan vasen ja oikea puoli',
		'The right-hand side only' => 'Ainoastaan oikea puoli',
		'The top and bottom sides only' => 'Ainoastaan ylä- ja alapuoli',
		'The top side only' => 'Ainoastaan yläpuoli',
		'Top' => 'Ylös',
		'Unset color' => 'Poista väri',
		'Vertical align' => 'Pystytasaus',
		'Width' => 'Leveys',
		'not-del-last-cell' => 'HTMLArea raukkamaisesti kieltäytyy poistamasta viimeistä solua riviltä.',
		'not-del-last-col' => 'HTMLArea raukkamaisesti kieltäytyy poistamasta viimeistä saraketta taulukosta.',
		'not-del-last-row' => 'HTMLArea raukkamaisesti kieltäytyy poistamasta viimeistä riviä taulukosta.',
		'percent' => 'prosenttia',
		'pixels' => 'Pixeliä',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>