<?php
/**
 * Language labels for plugin SpellChecker of RTE HtmalArea (extension: rte_pb_htmlarea)
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'Spell Checker' => 'Spell Checker',
		'CONFIRM_LINK_CLICK' => 'Please confirm that you want to open this link',
		'Cancel' => 'Cancel',
		'Dictionary' => 'Dictionary',
		'Finished list of mispelled words' => 'Finished list of mispelled words',
		'I will open it in a new page.' => 'I will open it in a new page.',
		'Ignore all' => 'Ignore all',
		'Ignore' => 'Ignore',
		'NO_ERRORS' => 'No mispelled words found with the selected dictionary.',
		'NO_ERRORS_CLOSING' => 'Spell check complete, didn\'t find any mispelled words.  Closing now...',
		'OK' => 'OK',
		'Original word' => 'Original word',
		'Please wait. Calling spell checker.' => 'Please wait. Calling spell checker.',
		'Please wait: changing dictionary to' => 'Please wait: changing dictionary to',
		'HTMLArea Spell Checker' => 'HTMLArea Spell Checker',
		'QUIT_CONFIRMATION' => 'This will drop changes and quit spell checker.  Please confirm.',
		'Re-check' => 'Re-check',
		'Replace all' => 'Replace all',
		'Replace with' => 'Replace with',
		'Replace' => 'Replace',
		'Revert' => 'Revert',
		'SC-spell-check' => 'Spell-check',
		'Suggestions' => 'Suggestions',
		'One occurrence' => 'One occurrence',
		'Two occurrences' => 'Two occurrences',
		'occurrences' => 'occurrences',
		'of the word' => 'of the word',
		'was found.' => 'was found.',
		'were found.' => 'were found.',
		'Document information' => 'Document information',
		'No information available' => 'No information available',
		'Total words' => 'Total words',
		'Misspelled words' => 'Misspelled words',
		'Total suggestions' => 'Total suggestions',
		'Total words suggested' => 'Total words suggested',
		'Spelling checked in' => 'Spelling checked in',
		'seconds' => 'seconds',
		'pliz weit ;-)' => 'pliz weit ;-)',
	),
	'dk' => Array (
	),
	'de' => Array (
		'Spell Checker' => 'Spell Checker',
		'CONFIRM_LINK_CLICK' => 'Bitte bestätigen Sie, dass Sie diesem Link folgen möchten',
		'Cancel' => 'Abbrechen',
		'Dictionary' => 'Wörterbuch',
		'Finished list of mispelled words' => 'Fertige Liste der Fehler',
		'I will open it in a new page.' => 'Ich werde eine neue Seite öffnen.',
		'Ignore all' => 'Alle ignorieren',
		'Ignore' => 'Ignorieren',
		'NO_ERRORS' => 'Im ausgewählten Wörterbuch wurden keine Fehler gefunden.',
		'NO_ERRORS_CLOSING' => 'Fehlersuche beendet, es wurden keine Fehler gefunden.  Die Suche wird nun beendet...',
		'OK' => 'OK',
		'Original word' => 'Ursprüngliches Wort',
		'Please wait. Calling spell checker.' => 'Bitte warten. Die Rechtschreibprüfung wird aufgerufen.',
		'Please wait: changing dictionary to' => 'Bitte warten: das Wörterbuch wird geändert nach',
		'HTMLArea Spell Checker' => 'HTMLArea Rechtschreibprüfung',
		'QUIT_CONFIRMATION' => 'Hierdurch werden die Änderungen verworfen und die Rechtschreibprüfung beendet. Bitte bestätigen.',
		'Re-check' => 'Nochmals prüfen',
		'Replace all' => 'Alle ersetzen',
		'Replace with' => 'Ersetzen durch',
		'Replace' => 'Ersetzen',
		'Revert' => 'Umkehren',
		'SC-spell-check' => 'Rechtschreibprüfung',
		'Suggestions' => 'Vorschläge',
		'One occurrence' => 'Einmal',
		'Two occurrences' => 'Zweimal',
		'occurrences' => 'Anzahl Vorkommen',
		'of the word' => 'des Wortes',
		'was found.' => 'wurde gefunden.',
		'were found.' => 'wurden gefunden.',
		'Document information' => 'Dokumentinformation',
		'No information available' => 'Keine information verfügbar',
		'Total words' => 'Totale Anzahl Wörter',
		'Misspelled words' => 'Fehlerhafte Wörter',
		'Total suggestions' => 'Total Anzahl Vorschläge',
		'Total words suggested' => 'Total Anzahl vorgeschlagener Wörter',
		'Spelling checked in' => 'Rechtschreibprüfung durchgeführt in',
		'seconds' => 'Sekunden',
		'pliz weit ;-)' => 'Bidde wahten ;-)',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
		'Spell Checker' => 'Vérificateur orthographique',
		'CONFIRM_LINK_CLICK' => 'Veuillez confirmer la demande d\'ouverture de ce lien',
		'Cancel' => 'Annuler',
		'Dictionary' => 'Dictionnaire',
		'Finished list of mispelled words' => 'La liste des mots mal orthographiés est terminée.',
		'I will open it in a new page.' => 'Ouverture dans une nouvelle page.',
		'Ignore all' => 'Ignorer tous',
		'Ignore' => 'Ignorer',
		'NO_ERRORS' => 'Aucune faute n\'a été trouvée avec le dictionnaire choisi.',
		'NO_ERRORS_CLOSING' => 'Vérification terminée, aucune erreur d\'orthographe n\'a été trouvée. Fermeture...',
		'OK' => 'Valider',
		'Original word' => 'Mot original',
		'Please wait. Calling spell checker.' => 'Veuillez patienter. Lancement du vérificateur orthographique.',
		'Please wait: changing dictionary to' => 'Veuillez patienter. Chargement du dictionnaire ',
		'HTMLArea Spell Checker' => 'HTMLArea - Vérificateur orthographique',
		'QUIT_CONFIRMATION' => 'Ceci va annuler tous les changements et quitter le vérificateur orthographique. Veuillez confirmer.',
		'Re-check' => 'Re-vérifier',
		'Replace all' => 'Remplacer partout',
		'Replace with' => 'Remplacer par',
		'Replace' => 'Remplacer',
		'Revert' => 'Rétablir',
		'SC-spell-check' => 'Vérifier l\'orthographe',
		'Suggestions' => 'Suggestions',
		'One occurrence' => 'Une occurrence',
		'Two occurrences' => 'Deux occurrences',
		'occurrences' => 'occurrences',
		'of the word' => 'du mot',
		'was found.' => 'a été trouvée.',
		'were found.' => 'ont été trouvées.',
		'Document information' => 'Information sur le document',
		'No information available' => 'Aucune information disponible',
		'Total words' => 'Nombre de mots dans le document',
		'Misspelled words' => 'Nombre de mots en erreur',
		'Total suggestions' => 'Nombre de suggestions',
		'Total words suggested' => 'Nombre total de mots suggérés',
		'Spelling checked in' => 'Vérification effectuée en',
		'seconds' => 'secondes',
		'pliz weit ;-)' => 'Veuillez patienter svp...',
	),
	'es' => Array (
		'Spell Checker' => 'Revisor ortográfico',
		'CONFIRM_LINK_CLICK' => 'Confirme que desea abrir este enlace',
		'Cancel' => 'Cancelar',
		'Dictionary' => 'Diccionario',
		'Finished list of mispelled words' => 'Se ha terminado la lista de palabras mal escritas',
		'I will open it in a new page.' => 'Lo abriré en una nueva página.',
		'Ignore all' => 'Ignorar todas',
		'Ignore' => 'Ignorar',
		'NO_ERRORS' => 'No se han encontrado palabras mal escritas según el diccionario seleccionado.',
		'NO_ERRORS_CLOSING' => 'Revisión ortográfica completada, no se encontraron palabras mal escritas. Cerrando...',
		'OK' => 'Aceptar',
		'Original word' => 'Palabra original',
		'Please wait. Calling spell checker.' => 'Espere. Llamando al revisor ortográfico.',
		'Please wait: changing dictionary to' => 'Espere: cambiando al diccionario',
		'HTMLArea Spell Checker' => 'HTMLArea - Revisor ortográfico',
		'QUIT_CONFIRMATION' => 'Esto anulará los cambios y se abandonará la revisión ortográfica. ¿Quiere continuar?',
		'Re-check' => 'Volver a revisar',
		'Replace all' => 'Sustituir todas',
		'Replace with' => 'Sustituir con',
		'Replace' => 'Sustituir',
		'Revert' => 'Restablecer',
		'SC-spell-check' => 'Revisar ortografía',
		'Suggestions' => 'Sugerencias',
		'One occurrence' => 'Una ocurrencia',
		'Two occurrences' => 'Dos ocurrencias',
		'occurrences' => 'ocurrencias',
		'of the word' => 'de la palabra',
		'was found.' => 'se ha encontrado.',
		'were found.' => 'se han encontrado.',
		'Document information' => 'Información sobre el documento',
		'No information available' => 'Ninguna información disponible',
		'Total words' => 'Número de palabras en el documento',
		'Misspelled words' => 'Número de palabras mal escritas',
		'Total suggestions' => 'Número de sugerencias',
		'Total words suggested' => 'Número total de palabras sugeridas',
		'Spelling checked in' => 'Revisión realizada en',
		'seconds' => 'segundos',
		'pliz weit ;-)' => 'Espere par favor...',
	),
	'nl' => Array (
		'Spell Checker' => 'Spellingscontrole',
		'CONFIRM_LINK_CLICK' => 'Bevestig AUB dat u deze link wilt openen',
		'Cancel' => 'Annuleren',
		'Dictionary' => 'Woordenboek',
		'Finished list of mispelled words' => 'Afgeronde lijst met verkeerd gespelde woorden',
		'I will open it in a new page.' => 'Ik zal het openen in een nieuwe pagina',
		'Ignore all' => 'Negeer alles',
		'Ignore' => 'Negeer',
		'NO_ERRORS' => 'Geen verkeerd gespelde woorden gevonden met het geselcteerde woordenboek',
		'NO_ERRORS_CLOSING' => 'Spellingscontrole compleet, geen verkeerd gespelde woorden gevonden. Bezig met afsluiten...',
		'OK' => 'OK',
		'Original word' => 'Origineel woord',
		'Please wait. Calling spell checker.' => 'Wachten AUB. Spellings controle wordt aangeroepen.',
		'Please wait: changing dictionary to' => 'Wachten AUB: woordenboek aan het veranderen naar',
		'HTMLArea Spell Checker' => 'HTMLArea Spellingscontrole',
		'QUIT_CONFIRMATION' => 'Dit zal de aanpassingen annuleren en de spellingscontrole afsluiten. Bevestig AUB.',
		'Re-check' => 'Opnieuw controleren',
		'Replace all' => 'Alles vervangen',
		'Replace with' => 'Vervangen met',
		'Replace' => 'Vervangen',
		'Revert' => 'Keer terug',
		'SC-spell-check' => 'Spellings-controle',
		'Suggestions' => 'Voorstellen',
		'One occurrence' => 'Een keer dat',
		'Two occurrences' => 'Twee keer dat',
		'occurrences' => 'keren dat',
		'of the word' => 'het woord',
		'was found.' => 'is gevonden',
		'were found.' => 'zijn gevonden.',
		'Document information' => 'Document informatie',
		'No information available' => 'Geen informatie beschikbaar',
		'Total words' => 'Totaal aantal woorden',
		'Misspelled words' => 'Fout gespelde woorden',
		'Total suggestions' => 'Totaal aantal voorstellen',
		'Total words suggested' => 'Totaal aantal voorgestelde woorden',
		'Spelling checked in' => 'Spelling gecontroleerd in',
		'seconds' => 'seconden',
		'pliz weit ;-)' => 'pliz weit ;-)',
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'Spell Checker' => 'Oikeinkirjotuksen tarkistus',
		'CONFIRM_LINK_CLICK' => 'Vahvista että haluat avata tämän linkin',
		'Cancel' => 'Peruuta',
		'Dictionary' => 'Sanakirja',
		'Finished list of mispelled words' => 'Väärinkirjoitettujen sanojen lista valmis',
		'I will open it in a new page.' => 'Avaan sen uudella sivulla',
		'Ignore all' => 'Ohita kaikki',
		'Ignore' => 'Ohita',
		'NO_ERRORS' => 'Valitulla sanakirjalla ei löytynyt väärinkirjoitettuja sanoja',
		'NO_ERRORS_CLOSING' => 'Oikoluku valmis',
		'OK' => 'OK',
		'Original word' => 'Alkuperäinen sana',
		'Please wait. Calling spell checker.' => 'Ole hyvä ja odota. Kutsumme oikolukua.',
		'Please wait: changing dictionary to' => 'Ole hyvä ja odota. vaihdamme sanakirjan',
		'HTMLArea Spell Checker' => 'HTMLArea oikoluku',
		'QUIT_CONFIRMATION' => 'Tämä unohtaa muutokset ja lopettaa oikoluvun. Ole hyvä ja vahvista.',
		'Re-check' => 'Tarkista uudelleen',
		'Replace all' => 'Korvaa kaikki',
		'Replace with' => 'Korvaa',
		'Replace' => 'Korvaa',
		'Revert' => 'Palauta',
		'SC-spell-check' => 'Oikolue',
		'Suggestions' => 'Ehdotukset',
		'One occurrence' => 'Yksi esiintymä',
		'Two occurrences' => 'Kaiksi esiintymää',
		'occurrences' => 'esiintymät',
		'of the word' => 'sanan',
		'was found.' => 'löytyi.',
		'were found.' => 'löytyi.',
		'Document information' => 'Asiakirjan tiedot',
		'No information available' => 'Ei tietoja saatavilla',
		'Total words' => 'Sanoja yhteensä',
		'Misspelled words' => 'Väärinkirjoitettuja sanoja',
		'Total suggestions' => 'Ehdotuksia yhteensä',
		'Total words suggested' => 'Ehdotettuja sanoja yhteensä',
		'Spelling checked in' => 'Oikoluvussa tarkistettiin',
		'seconds' => 'sekuntia',
		'pliz weit ;-)' => 'Ole hyvä ja odota.',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>